remote_theme: onetrackconsulting/minimal
title: One Track Consulting, LLC
description: >- 
  When the path you're on is the one that matters.
logo: images/OneTrack_rgb.png
github:
  is_user_page: true
  owner_url: https://github.com/AlexCuse

theme: jekyll-theme-minimal